const onlineTranslations = <String, Map<String, String>>{
  'yourCareer': {
    'en': 'Your current career',
    'es': 'Tu carrera actual',
    'pt-BR': 'Sua carreira atual',
    'fr': 'Votre carrière actuelle',
  },

  'trainingLight': {
    'en': 'Light',
    'es': 'Ligero',
    'pt-BR': 'Leve',
    'fr': 'Léger',
  },
  'trainingIntensive': {
    'en': 'Intensive',
    'es': 'Intensivo',
    'pt-BR': 'Intensivo',
    'fr': 'Intensif',
  },
  'archivePending': {
    'en': 'Your retired career is archived on this device. Cloud backup is pending; retry sync when online.',
    'es': 'Tu carrera retirada está archivada en este dispositivo. La copia en la nube está pendiente; vuelve a sincronizar con conexión.',
    'pt-BR': 'Sua carreira aposentada está arquivada neste dispositivo. A cópia na nuvem está pendente; sincronize ao conectar.',
    'fr': 'Votre carrière terminée est archivée sur cet appareil. La copie dans le cloud est en attente ; réessayez la synchronisation en ligne.',
  },
  "support": {
    "en": "Support and feedback",
    "es": "Ayuda y comentarios",
    "pt-BR": "Ajuda e feedback",
    "fr": "Assistance et avis",
  },
  "supportBody": {
    "en": "Report a problem or suggest an improvement. Your career stays on this device.",
    "es": "Informa de un problema o sugiere una mejora. Tu carrera sigue en este dispositivo.",
    "pt-BR": "Relate um problema ou sugira uma melhoria. Sua carreira fica neste dispositivo.",
    "fr": "Signalez un problème ou proposez une amélioration. Votre carrière reste sur cet appareil.",
  },
  "bug": {
    "en": "Report a bug",
    "es": "Informar de un error",
    "pt-BR": "Relatar um erro",
    "fr": "Signaler un problème",
  },
  "feature": {
    "en": "Suggest a feature",
    "es": "Sugerir una función",
    "pt-BR": "Sugerir uma função",
    "fr": "Proposer une fonction",
  },
  "purchase": {
    "en": "Purchase help",
    "es": "Ayuda con compras",
    "pt-BR": "Ajuda com compras",
    "fr": "Aide aux achats",
  },
  "other": {"en": "Other", "es": "Otro", "pt-BR": "Outro", "fr": "Autre"},
  "message": {
    "en": "Your message",
    "es": "Tu mensaje",
    "pt-BR": "Sua mensagem",
    "fr": "Votre message",
  },
  "email": {
    "en": "Reply email (optional)",
    "es": "Correo de respuesta (opcional)",
    "pt-BR": "E-mail para resposta (opcional)",
    "fr": "E-mail de réponse (facultatif)",
  },
  "reviewDiagnostics": {
    "en": "Include the diagnostics shown below",
    "es": "Incluir los datos de diagnóstico siguientes",
    "pt-BR": "Incluir os dados de diagnóstico abaixo",
    "fr": "Inclure les données de diagnostic ci-dessous",
  },
  "diagnostics": {
    "en": "Review diagnostics",
    "es": "Revisar diagnóstico",
    "pt-BR": "Revisar diagnóstico",
    "fr": "Vérifier le diagnostic",
  },
  "send": {"en": "Send", "es": "Enviar", "pt-BR": "Enviar", "fr": "Envoyer"},
  "received": {
    "en": "Your report was received.",
    "es": "Tu informe se ha recibido.",
    "pt-BR": "Seu relato foi recebido.",
    "fr": "Votre demande a été reçue.",
  },
  "failed": {
    "en": "Could not complete the request. Your progress is safe. Try again.",
    "es": "No se pudo completar la solicitud. Tu progreso está a salvo. Inténtalo de nuevo.",
    "pt-BR": "Não foi possível concluir a solicitação. Seu progresso está seguro. Tente novamente.",
    "fr": "Impossible de terminer la demande. Votre progression est conservée. Réessayez.",
  },
  "retry": {
    "en": "Retry",
    "es": "Reintentar",
    "pt-BR": "Tentar novamente",
    "fr": "Réessayer",
  },
  "invalidMessage": {
    "en": "Enter between 10 and 2000 characters.",
    "es": "Escribe entre 10 y 2000 caracteres.",
    "pt-BR": "Escreva entre 10 e 2000 caracteres.",
    "fr": "Saisissez entre 10 et 2000 caractères.",
  },
  "invalidEmail": {
    "en": "Enter a valid email or leave this empty.",
    "es": "Introduce un correo válido o deja el campo vacío.",
    "pt-BR": "Digite um e-mail válido ou deixe em branco.",
    "fr": "Saisissez un e-mail valide ou laissez ce champ vide.",
  },
  "friends": {"en": "Friends", "es": "Amigos", "pt-BR": "Amigos", "fr": "Amis"},
  "friendsBody": {
    "en": "Invite people you know to compare careers privately. Both players choose whether to share statistics.",
    "es": "Invita a personas conocidas para comparar carreras en privado. Ambos eligen si comparten estadísticas.",
    "pt-BR": "Convide pessoas conhecidas para comparar carreiras em privado. Ambos escolhem se compartilham estatísticas.",
    "fr": "Invitez vos proches pour comparer vos carrières en privé. Chaque joueur choisit de partager ses statistiques.",
  },
  "friendConsent": {
    "en": "Share career statistics with accepted friends",
    "es": "Compartir estadísticas con amigos aceptados",
    "pt-BR": "Compartilhar estatísticas com amigos aceitos",
    "fr": "Partager mes statistiques avec mes amis acceptés",
  },
  "invite": {
    "en": "Create an invitation code",
    "es": "Crear código de invitación",
    "pt-BR": "Criar código de convite",
    "fr": "Créer un code d’invitation",
  },
  "copy": {"en": "Copy", "es": "Copiar", "pt-BR": "Copiar", "fr": "Copier"},
  "inviteCode": {
    "en": "Invitation code",
    "es": "Código de invitación",
    "pt-BR": "Código de convite",
    "fr": "Code d’invitation",
  },
  "requestFriend": {
    "en": "Send friend request",
    "es": "Enviar solicitud",
    "pt-BR": "Enviar solicitação",
    "fr": "Envoyer une demande",
  },
  "incoming": {
    "en": "Incoming requests",
    "es": "Solicitudes recibidas",
    "pt-BR": "Solicitações recebidas",
    "fr": "Demandes reçues",
  },
  "outgoing": {
    "en": "Sent requests",
    "es": "Solicitudes enviadas",
    "pt-BR": "Solicitações enviadas",
    "fr": "Demandes envoyées",
  },
  "accept": {
    "en": "Accept",
    "es": "Aceptar",
    "pt-BR": "Aceitar",
    "fr": "Accepter",
  },
  "decline": {
    "en": "Decline",
    "es": "Rechazar",
    "pt-BR": "Recusar",
    "fr": "Refuser",
  },
  "remove": {
    "en": "Remove friend",
    "es": "Eliminar amigo",
    "pt-BR": "Remover amigo",
    "fr": "Retirer cet ami",
  },
  "block": {
    "en": "Block",
    "es": "Bloquear",
    "pt-BR": "Bloquear",
    "fr": "Bloquer",
  },
  "unblock": {
    "en": "Unblock",
    "es": "Desbloquear",
    "pt-BR": "Desbloquear",
    "fr": "Débloquer",
  },
  "blocked": {
    "en": "Blocked profiles",
    "es": "Perfiles bloqueados",
    "pt-BR": "Perfis bloqueados",
    "fr": "Profils bloqués",
  },
  "comparisonPrivate": {
    "en": "Statistics are private until both players enable sharing.",
    "es": "Las estadísticas son privadas hasta que ambos activen compartir.",
    "pt-BR":
        "As estatísticas são privadas até ambos ativarem o compartilhamento.",
    "fr": "Les statistiques restent privées jusqu’à l’accord des deux joueurs.",
  },
  "noFriends": {
    "en": "No friends yet. Share an invitation code to get started.",
    "es": "Aún no tienes amigos. Comparte un código para empezar.",
    "pt-BR": "Ainda não há amigos. Compartilhe um código para começar.",
    "fr": "Aucun ami pour le moment. Partagez un code pour commencer.",
  },
  "signIn": {
    "en": "Sign in",
    "es": "Iniciar sesión",
    "pt-BR": "Entrar",
    "fr": "Se connecter",
  },
  "signInBody": {
    "en": "Sign in to use this online feature. Your offline careers remain available.",
    "es": "Inicia sesión para usar esta función. Tus carreras sin conexión siguen disponibles.",
    "pt-BR": "Entre para usar esta função. Suas carreiras offline continuam disponíveis.",
    "fr": "Connectez-vous pour utiliser cette fonction. Vos carrières hors ligne restent disponibles.",
  },
  "myRank": {
    "en": "My rank",
    "es": "Mi posición",
    "pt-BR": "Minha posição",
    "fr": "Mon classement",
  },
  "nearby": {
    "en": "Nearby rivals",
    "es": "Rivales cercanos",
    "pt-BR": "Rivais próximos",
    "fr": "Rivaux proches",
  },
  "topPlayers": {
    "en": "Top players",
    "es": "Mejores jugadores",
    "pt-BR": "Melhores jogadores",
    "fr": "Meilleurs joueurs",
  },
  "rankPending": {
    "en": "Your career needs a successful cloud sync and sharing enabled to appear here.",
    "es": "Tu carrera necesita sincronizarse con la nube y tener compartir activado para aparecer aquí.",
    "pt-BR": "Sua carreira precisa sincronizar com a nuvem e ter o compartilhamento ativo para aparecer aqui.",
    "fr": "Votre carrière doit être synchronisée et son partage activé pour apparaître ici.",
  },
  "challenge": {
    "en": "Weekly challenge",
    "es": "Desafío semanal",
    "pt-BR": "Desafio semanal",
    "fr": "Défi hebdomadaire",
  },
  "challengeTitle": {
    "en": "Eight-match breakthrough",
    "es": "Salto en ocho partidos",
    "pt-BR": "Destaque em oito partidas",
    "fr": "Percée en huit matchs",
  },
  "challengeBody": {
    "en": "Play eight matches from the same starting point as everyone else. One attempt each week, identical progression, no prizes. Your regular career is separate.",
    "es": "Juega ocho partidos desde el mismo punto inicial que todos. Un intento semanal, progresión idéntica y sin premios. Tu carrera habitual es independiente.",
    "pt-BR": "Jogue oito partidas do mesmo ponto inicial. Uma tentativa por semana, progressão idêntica e sem prêmios. Sua carreira normal é independente.",
    "fr": "Jouez huit matchs depuis le même point de départ. Un essai par semaine, progression identique et aucun prix. Votre carrière habituelle reste séparée.",
  },
  "startChallenge": {
    "en": "Start this week’s challenge",
    "es": "Empezar desafío semanal",
    "pt-BR": "Começar desafio semanal",
    "fr": "Commencer le défi de la semaine",
  },
  "playMatch": {
    "en": "Play next match",
    "es": "Jugar siguiente partido",
    "pt-BR": "Jogar próxima partida",
    "fr": "Jouer le prochain match",
  },
  "submitChallenge": {
    "en": "Submit results",
    "es": "Enviar resultados",
    "pt-BR": "Enviar resultados",
    "fr": "Envoyer les résultats",
  },
  "challengeSaved": {
    "en": "Your choices are saved on this device. Results appear after server verification.",
    "es": "Tus elecciones se guardan en este dispositivo. Los resultados aparecen tras su verificación.",
    "pt-BR": "Suas escolhas ficam neste dispositivo. Os resultados aparecem após a verificação do servidor.",
    "fr": "Vos choix sont enregistrés sur cet appareil. Les résultats apparaissent après vérification du serveur.",
  },
  "challengeSubmitted": {
    "en": "Results verified and submitted.",
    "es": "Resultados verificados y enviados.",
    "pt-BR": "Resultados verificados e enviados.",
    "fr": "Résultats vérifiés et envoyés.",
  },
  "challengeExpired": {
    "en": "This challenge has closed. Return for the next challenge.",
    "es": "Este desafío ha terminado. Vuelve para el siguiente.",
    "pt-BR": "Este desafio terminou. Volte para o próximo.",
    "fr": "Ce défi est terminé. Revenez pour le prochain.",
  },
  "challengeIncompatible": {
    "en": "Update the app to play this challenge.",
    "es": "Actualiza la aplicación para jugar este desafío.",
    "pt-BR": "Atualize o aplicativo para jogar este desafio.",
    "fr": "Mettez l’application à jour pour jouer ce défi.",
  },
  "score": {
    "en": "Score",
    "es": "Puntuación",
    "pt-BR": "Pontuação",
    "fr": "Score",
  },
  "ends": {"en": "Closes", "es": "Cierra", "pt-BR": "Termina", "fr": "Fin"},
  "matches": {
    "en": "Matches",
    "es": "Partidos",
    "pt-BR": "Partidas",
    "fr": "Matchs",
  },
  "focus": {
    "en": "Training focus",
    "es": "Enfoque de entrenamiento",
    "pt-BR": "Foco de treino",
    "fr": "Objectif d’entraînement",
  },
  "load": {
    "en": "Training load",
    "es": "Carga de entrenamiento",
    "pt-BR": "Carga de treino",
    "fr": "Charge d’entraînement",
  },
  "approach": {
    "en": "Match approach",
    "es": "Enfoque del partido",
    "pt-BR": "Abordagem da partida",
    "fr": "Approche du match",
  },
  "noEntries": {
    "en": "No results yet.",
    "es": "Aún no hay resultados.",
    "pt-BR": "Ainda não há resultados.",
    "fr": "Aucun résultat pour le moment.",
  },
  "confirm": {
    "en": "Confirm",
    "es": "Confirmar",
    "pt-BR": "Confirmar",
    "fr": "Confirmer",
  },
  "cancel": {
    "en": "Cancel",
    "es": "Cancelar",
    "pt-BR": "Cancelar",
    "fr": "Annuler",
  },
  "challengeRules": {
    "en": "Score: league points × 100 + match ratings × 10 + goals × 15 + assists × 10.",
    "es": "Puntos: puntos de liga × 100 + notas × 10 + goles × 15 + asistencias × 10.",
    "pt-BR": "Pontuação: pontos de liga × 100 + notas × 10 + gols × 15 + assistências × 10.",
    "fr": "Score : points de championnat × 100 + notes × 10 + buts × 15 + passes décisives × 10.",
  },
};

String onlineCopy(String locale, String key) =>
    onlineTranslations[key]?[locale] ?? onlineTranslations[key]?['en'] ?? key;
